name: flackjack
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  audio_manager: ^0.8.2
  audioplayers: ^4.0.1
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  flutter:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: any
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  panara_dialogs: ^0.1.4
  velocity_x: ^3.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "BlackJack"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
